import Head from "next/head";
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";
import Products from "@/components/Product";
import { Product } from "@/type";
import Footer from "@/components/Footer";
import { TopFooter } from "@/components/TopFooter";

interface Props {
  products: Product[];
} 

export default async function Page() {
  const products: Props = await fatchData()
 // console.log(products)
  return (
    <>
    <Head >
       <title> Shoppers.com | Save Money. Live Batter </title>
       <meta name="description " content="Generated by create next app" />
       <meta  name="viewport" content="width=device-width, initial-scale=1"/>
       <link rel="icon" href="/smallLogo.ico" />
    </Head>
    <main className="bg-lighBlue">
      <Navbar />
      <div className="max-w-contenetContainer mx-auto bg-white">  
        <Banner />
        <Products product={products} />
      </div>
      <TopFooter />
      <Footer />
    </main>
    </>
  );
}

/* =============== SSR data fetching oled methode=================== */

/* async function getProducts(postId: string) {
  const response = await fetch("http://localhost:3000/api/products", {
    method: "GET",
  });
  return response
}

export  async function PostId ({ params }: any) {
  const products = await getProducts(params.id);
  return products
}
 */
/* =============== SSR data fetching new method  =================== */
async function fatchData() {
  const prodectResponse = await fetch("http://localhost:3000/api/products", {
    // cache: "force-cache", // < SSG getStaticProps
     cache: "no-cache", // < SSR   getServerSideProps
    // next: {
    //   revalidate: 10, // < ISR revalidate
    //  },
  })
  // await wait (4000);
  console.log("fatching Product");
  return prodectResponse.json()
}

